services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapppassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && if [ \"$RAILS_ENV\" = 'production' ]; then bundle exec rails assets:precompile; fi && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      MYSQL_PASSWORD: password
      MECAB_PATH: /usr/lib/aarch64-linux-gnu/libmecab.so # Add this line
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  mysql_data:
  bundle_data:
  node_modules: